
// Generated by Cadence Genus(TM) Synthesis Solution 16.13-s036_1
// Generated on: Feb 20 2023 00:19:47 BDT (Feb 19 2023 18:19:47 UTC)

// Verification Directory fv/extend 

module extend(instr, immsrc, immext);
  input [31:7] instr;
  input [2:0] immsrc;
  output [31:0] immext;
  wire [31:7] instr;
  wire [2:0] immsrc;
  wire [31:0] immext;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_23;
  wire n_26, n_31, n_32, n_42, n_85;
  assign immext[31] = instr[31];
  OAI2BB1X1 g669(.A0N (instr[19]), .A1N (n_42), .B0 (n_85), .Y
       (immext[19]));
  OAI2BB1X1 g670(.A0N (instr[18]), .A1N (n_42), .B0 (n_85), .Y
       (immext[18]));
  OAI2BB1X1 g671(.A0N (instr[17]), .A1N (n_42), .B0 (n_85), .Y
       (immext[17]));
  OAI2BB1X1 g668(.A0N (instr[16]), .A1N (n_42), .B0 (n_85), .Y
       (immext[16]));
  OAI2BB1X1 g672(.A0N (instr[15]), .A1N (n_42), .B0 (n_85), .Y
       (immext[15]));
  OAI2BB1X1 g676(.A0N (instr[14]), .A1N (n_42), .B0 (n_85), .Y
       (immext[14]));
  OAI2BB1X1 g675(.A0N (instr[13]), .A1N (n_42), .B0 (n_85), .Y
       (immext[13]));
  OAI2BB1X1 g674(.A0N (instr[12]), .A1N (n_42), .B0 (n_85), .Y
       (immext[12]));
  AO22XL g664(.A0 (instr[24]), .A1 (n_32), .B0 (instr[11]), .B1 (n_31),
       .Y (immext[4]));
  AO22XL g665(.A0 (instr[23]), .A1 (n_32), .B0 (instr[10]), .B1 (n_31),
       .Y (immext[3]));
  AO22XL g666(.A0 (instr[22]), .A1 (n_32), .B0 (instr[9]), .B1 (n_31),
       .Y (immext[2]));
  AO22XL g667(.A0 (instr[21]), .A1 (n_32), .B0 (instr[8]), .B1 (n_31),
       .Y (immext[1]));
  OAI211X1 g677(.A0 (n_23), .A1 (immsrc[1]), .B0 (n_9), .C0 (n_6), .Y
       (immext[11]));
  INVX1 g673(.A (n_26), .Y (immext[0]));
  AOI32X1 g678(.A0 (instr[7]), .A1 (immsrc[0]), .A2 (n_8), .B0
       (instr[20]), .B1 (n_11), .Y (n_26));
  OAI21X1 g680(.A0 (immsrc[2]), .A1 (n_10), .B0 (n_12), .Y (n_32));
  OAI2BB1X1 g687(.A0N (instr[30]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[30]));
  OAI2BB1X1 g694(.A0N (instr[29]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[29]));
  OAI2BB1X1 g690(.A0N (instr[28]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[28]));
  OAI2BB1X1 g693(.A0N (instr[27]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[27]));
  OAI2BB1X1 g697(.A0N (instr[26]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[26]));
  OAI2BB1X1 g691(.A0N (instr[25]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[25]));
  OAI2BB1X1 g692(.A0N (instr[24]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[24]));
  OAI2BB1X1 g689(.A0N (instr[23]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[23]));
  OAI2BB1X1 g695(.A0N (instr[22]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[22]));
  OAI2BB1X1 g696(.A0N (instr[21]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[21]));
  OAI2BB1X1 g688(.A0N (instr[20]), .A1N (immsrc[2]), .B0 (n_23), .Y
       (immext[20]));
  INVX1 g682(.A (n_11), .Y (n_12));
  NAND2X1 g685(.A (n_7), .B (n_10), .Y (n_42));
  NAND2BX1 g681(.AN (n_10), .B (instr[20]), .Y (n_9));
  MXI2XL g698(.A (n_8), .B (immsrc[1]), .S0 (immsrc[0]), .Y (n_31));
  NAND2X2 g706(.A (instr[31]), .B (n_7), .Y (n_23));
  NAND3BXL g686(.AN (immsrc[0]), .B (instr[7]), .C (immsrc[1]), .Y
       (n_6));
  NOR3X1 g684(.A (immsrc[0]), .B (immsrc[1]), .C (immsrc[2]), .Y
       (n_11));
  NOR2BX1 g702(.AN (instr[25]), .B (immsrc[2]), .Y (immext[5]));
  NOR2BX1 g704(.AN (instr[28]), .B (immsrc[2]), .Y (immext[8]));
  NAND2X1 g705(.A (immsrc[0]), .B (immsrc[1]), .Y (n_10));
  NOR2BX1 g700(.AN (instr[29]), .B (immsrc[2]), .Y (immext[9]));
  NOR2BX1 g701(.AN (instr[30]), .B (immsrc[2]), .Y (immext[10]));
  NOR2BX1 g703(.AN (instr[26]), .B (immsrc[2]), .Y (immext[6]));
  NOR2BX1 g699(.AN (instr[27]), .B (immsrc[2]), .Y (immext[7]));
  INVX1 g707(.A (immsrc[1]), .Y (n_8));
  INVX1 g708(.A (immsrc[2]), .Y (n_7));
  NAND2BX1 g2(.AN (n_42), .B (instr[31]), .Y (n_85));
endmodule

